version: "3"
services:
  web:
    image: jerturowetz/get-started:page2
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
